#' Read All Sheets from an Excel Workbook
#'
#' Reads all sheets or a selected subset from an Excel workbook and
#' returns a structured `excel_book` S3 object.
#'
#' The function provides a controlled abstraction layer over the
#' `readxl` and `openxlsx` packages. It performs input validation,
#' dependency checking, workbook discovery, sheet selection and
#' sheet-level error isolation.
#'
#' The returned object preserves workbook structure and failed sheet
#' information, supporting reproducibility and traceability in
#' production environments.
#'
#' @param filename Character scalar. Path to the Excel workbook.
#'
#' @param engine Character scalar. Excel reading backend.
#' Supported values are:
#' \code{"readxl"} (default) and \code{"openxlsx"}.
#'
#' @param sheet_names Optional sheet selection.
#' Accepts:
#' \itemize{
#'   \item \code{NULL}: read all sheets;
#'   \item character vector: sheet names;
#'   \item numeric vector: 1-based sheet positions.
#' }
#'
#' @param guess_max Numeric scalar. Maximum number of rows used by
#' `readxl` for column type inference.
#'
#' @param parallel Logical scalar.
#' Reserved for future parallel execution support.
#'
#' @param tibble Logical scalar.
#' If TRUE, keeps tibble output generated by `readxl`.
#'
#' @param verbose Logical scalar.
#' If TRUE, displays execution messages.
#'
#' @param return_failed Logical scalar.
#' Retained for backward compatibility.
#' Failed sheets are always available through the returned
#' `excel_book` object.
#'
#' @param ... Additional arguments passed to the underlying reader.
#'
#' @return
#' An object of class `excel_book`.
#'
#' The object contains:
#' \itemize{
#'   \item imported sheets (`excel_sheet` objects);
#'   \item failed sheet information;
#'   \item workbook metadata.
#' }
#'
#' @seealso
#' \code{\link{new_excel_book}},
#' \code{\link{new_excel_sheet}},
#' \code{\link{snapshot_excel}},
#' \code{\link{file_fingerprint}}
#'
#' @export
read_excel_allsheets <- function(
    filename,
    engine = "readxl",
    sheet_names = NULL,
    guess_max = 10000,
    parallel = FALSE,
    tibble = FALSE,
    verbose = FALSE,
    return_failed = FALSE,
    ...
) {


  # -------------------------------------------------------------------------
  # 1. Validate user inputs
  # -------------------------------------------------------------------------

  validate_read_excel_inputs(
    filename = filename,
    engine = engine,
    sheet_names = sheet_names,
    guess_max = guess_max,
    parallel = parallel,
    tibble = tibble,
    verbose = verbose,
    return_failed = return_failed
  )



  engine <- match.arg(
    engine,
    c(
      "readxl",
      "openxlsx"
    )
  )



  # -------------------------------------------------------------------------
  # 2. Validate required dependencies
  # -------------------------------------------------------------------------

  validate_dependencies(engine)



  # -------------------------------------------------------------------------
  # 3. Discover workbook structure
  # -------------------------------------------------------------------------

  workbook_info <- discover_workbook(
    filename = filename,
    engine = engine,
    verbose = verbose
  )



  # -------------------------------------------------------------------------
  # 4. Select sheets to import
  # -------------------------------------------------------------------------

  selected_sheets <- select_sheets(
    all_sheets = workbook_info$sheets,
    sheet_names = sheet_names
  )



  if(length(selected_sheets)==0){

    warning(
      "No valid worksheets selected.",
      call.=FALSE
    )

    return(
      new_excel_book()
    )

  }



  # -------------------------------------------------------------------------
  # 5. Import worksheets
  # -------------------------------------------------------------------------

  book <- read_selected_sheets(
    filename = filename,
    sheets = selected_sheets,
    engine = engine,
    guess_max = guess_max,
    tibble = tibble,
    verbose = verbose,
    ...
  )



  # -------------------------------------------------------------------------
  # 6. Attach workbook metadata
  # -------------------------------------------------------------------------

  book$metadata <- c(

    book$metadata,

    list(

      filename = filename,

      engine = engine,

      requested_sheets = sheet_names,

      available_sheets =
        workbook_info$sheets

    )

  )



  book

}
